### ISSUE TITLE
Fix KafkaAnalyzer and implement CI/CD with branch protection

### ISSUE THREAD

**Issue by emilholmegaard** [emilholmegaard/sokrates-kafka-viz#23]
The current KafkaAnalyzer is missing the required analyze_service() method, causing runtime errors. Additionally, we need better test coverage and CI/CD protection.

## Current Issues
1. Missing `analyze_service()` implementation
2. Lack of integration tests
3. No branch protection on main
4. No automated CI/CD validation

### 1. KafkaAnalyzer Implementation
```python
class KafkaAnalyzer:
    def __init__(self):
        self.topic_patterns = {
            'java': [
                r'@KafkaListener\(\s*topics\s*=\s*["\']([^"\']+)["\']',
                r'@SendTo\(\s*["\']([^"\']+)["\']',
                r'new\s+KafkaTemplate<>\([^)]+\).send\(\s*["\']([^"\']+)["\']'
            ],
            'python': [
                r'KafkaConsumer\([^)]*["\']([^"\']+)["\']',
                r'KafkaProducer\(\).send\(\s*["\']([^"\']+)["\']'
            ],
            'javascript': [
                r'kafka\.consumer\([^)]*["\']([^"\']+)["\']',
                r'kafka\.producer\.send\([^)]*["\']([^"\']+)["\']'
            ]
        }
        
    def analyze_service(self, service: Service) -> None:
        """Analyze a service for Kafka usage.
        
        Args:
            service: Service to analyze
        """
        for file_path in service.root_path.rglob('*'):
            if self._is_source_file(file_path):
                self._analyze_file(service, file_path)
                
    def _analyze_file(self, service: Service, file_path: Path) -> None:
        """Analyze a single file for Kafka patterns."""
        with open(file_path) as f:
            content = f.read()
            
        patterns = self.topic_patterns.get(service.language, [])
        for pattern in patterns:
            for match in re.finditer(pattern, content):
                topic_name = match.group(1)
                if topic_name not in service.topics:
                    service.topics[topic_name] = KafkaTopic(topic_name)
                    
                # Determine if producer or consumer based on pattern
                if any(p in pattern for p in ['send', 'SendTo', 'producer']):
                    service.topics[topic_name].producers.add(service.name)
                else:
                    service.topics[topic_name].consumers.add(service.name)
```

### 2. Integration Tests
Create test suite in `tests/integration/`:
```python
# tests/integration/test_analysis.py

def test_end_to_end_analysis(tmp_path):
    """Test complete analysis process."""
    # Create test services
    services_dir = create_test_services(tmp_path)
    
    # Run analysis
    result = run_cli_analysis(services_dir)
    
    # Verify output
    assert result.exit_code == 0
    validate_analysis_output(result.output_file)
    
def test_kafka_analyzer_java():
    """Test Kafka pattern detection in Java code."""
    service = create_java_service(
        '''
        @KafkaListener(topics = "orders")
        public void processOrder(OrderEvent event) {
            // Process order
            template.send("notifications", new NotificationEvent());
        }
        '''
    )
    
    analyzer = KafkaAnalyzer()
    analyzer.analyze_service(service)
    
    assert "orders" in service.topics
    assert "notifications" in service.topics
    assert service.name in service.topics["orders"].consumers
    assert service.name in service.topics["notifications"].producers
```

### 3. CI/CD Pipeline
Add GitHub Actions workflow:
```yaml
name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10"]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
        
    - name: Run tests
      run: |
        pytest --cov=kafka_viz tests/
        
    - name: Type checking
      run: |
        mypy kafka_viz
        
    - name: Lint
      run: |
        black --check kafka_viz tests
        isort --check kafka_viz tests
        flake8 kafka_viz tests

  integration:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Integration tests
      run: |
        pytest tests/integration/

  build:
    needs: [test, integration]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Build package
      run: |
        pip install build
        python -m build
```

### 4. Branch Protection Rules
Configure in GitHub repository settings:
1. Require pull request reviews before merging
2. Require status checks to pass before merging:
   - CI test suite
   - Integration tests
   - Build checks
3. Require branches to be up to date
4. Include administrators in restrictions

## Implementation Steps
1. Implement KafkaAnalyzer.analyze_service()
2. Add integration test suite
3. Set up GitHub Actions workflow
4. Configure branch protection rules
5. Add documentation for development workflow

## Additional Recommendations
1. Add test coverage requirements (e.g., minimum 80%)
2. Add performance benchmarks to CI pipeline
3. Implement automatic version bumping
4. Add automatic changelog generation
5. Set up automatic release creation
